spring:
  profiles:
    group:
      local: local-db, common
      dev: dev-db, common
#      prod: prod-db, common

---
# local, dev, prod 공통 설정
spring:
  config:
    activate:
      on-profile: common

server:
  port: 8085

---
# local
spring:
  config:
    activate:
      on-profile: local-db
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
    redis:
      host: localhost
      port: 6379

---
# dev
spring:
  config:
    activate:
      on-profile: dev-db
  data:
    mongodb:
      host: ${MONGODB_HOST}
      port: 27017
      authentication-database: admin
      database: chatting
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
    redis:
      host: ${REDIS_HOST}
      port: 6379

---

#logging:
#  level:
#    root: debug

#logging:
#  level:
#    org.springframework.data.mongodb: DEBUG